---
- name: Upload firmware to Aruba switch with VSF auto-stacking and reboot
  hosts: Ansible_test
  gather_facts: no
  connection: httpapi
  vars:
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443  # change if needed
    timeout_minutes: 60
    wait_minutes: 5
    vsf_wait_minutes: 10  # Time to wait for VSF stacking to complete

  tasks:
    # Step 0: Check for VSF partners and start auto-stacking if needed
    - name: Step 0a - Check for VSF partner switches
      shell: |
        timeout 15 sshpass -p "{{ ansible_password }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ ansible_host }} "show vsf"
      register: vsf_status
      delegate_to: localhost
      ignore_errors: yes

    - name: Show current VSF status
      debug:
        var: vsf_status.stdout_lines
      when: vsf_status.rc == 0

    - name: Check if VSF partners are detected
      set_fact:
        has_vsf_partners: "{{ 'Partner' in vsf_status.stdout or 'partner' in vsf_status.stdout or 'Fragment' in vsf_status.stdout }}"
      when: vsf_status.rc == 0

    - name: Set VSF partners flag to false if command failed
      set_fact:
        has_vsf_partners: false
      when: vsf_status.rc != 0

    - name: VSF partner detection result
      debug:
        msg: |
          {% if has_vsf_partners %}
          🔍 VSF partners detected - will initiate auto-stacking
          {% else %}
          ℹ️  No VSF partners detected - skipping auto-stacking
          {% endif %}

    - name: Step 0b - Start VSF auto-stacking (only if partners detected)
      shell: |
        timeout 30 bash -c 'echo -e "vsf start-auto-stacking\ny\nexit" | sshpass -p "{{ ansible_password }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ ansible_host }}'
      register: vsf_start_result
      delegate_to: localhost
      ignore_errors: yes
      when: has_vsf_partners | default(false)

    - name: Show VSF auto-stacking command result
      debug:
        var: vsf_start_result.stdout_lines
      when: has_vsf_partners | default(false) and vsf_start_result is defined

    - name: Wait for VSF stacking to complete
      debug:
        msg: "⏳ Waiting {{ vsf_wait_minutes }} minutes for VSF auto-stacking to complete..."
      when: has_vsf_partners | default(false)

    - name: Sleep for VSF completion
      pause:
        minutes: "{{ vsf_wait_minutes }}"
"stack_and_update.yml" 213L, 8511B                                                                                                                                                                                                                        1,1           Top
